### PR TITLE
fix: improve regex matching

### LINKED ISSUE #2: It matches dot `.` It shouldn't :)
**Describe the bug**

Seen this `Updating DCOS-21233.` in our logs. Note the dot character at the end. Because of the dot at the end it couldn't find the ticket and didn't update it.

Messages to consider:
```
Closes: JIRA-1234
Close JIRA-1234
closes JIRA-1234.
```

### PR DESCRIPTION
**Pull request by juliangieseke**
closes #2

### CODE REVIEW

File: src/functions/parseCommitBody.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ const parseCommitBody = function(body) {
     return [];
   }
 
-  const regEx = /((updates|resolves|closes)\s(\"[^\"]+\"|[^,\s]+))/gi;
+  const regEx = /((updates?|resolves?|closes?):? \"?([A-Z]+.[0-9]+)\"?)/gi;
```
Comment (juliangieseke) [inline src/functions/parseCommitBody.js]: throw this regex in something like https://regex101.com/ for sanity check

File: src/functions/parseCommitBody.js [hunk 2]
```diff
@@ -18,11 +18,14 @@ const parseCommitBody = function(body) {
...
 
-  return matches !== null
-    ? matches.map(match =>
-        match.replace(/\"|updates|resolves|closes\s/gi, "").trim()
-      )
-    : [];
+  const issues =
+    matches !== null
+      ? matches.map(match =>
+          match.replace(/\"|updates?|resolves?|closes?:?\s/gi, "").trim()
```
Comment (juliangieseke) [inline src/functions/parseCommitBody.js:24]: throw this regex in something like https://regex101.com/ for sanity check

File: src/functions/parseCommitBody.js [hunk 3]
```diff
@@ -9,7 +9,7 @@ const parseCommitBody = function(body) {
     return [];
   }
 
-  const regEx = /((updates|resolves|closes)\s(\"[^\"]+\"|[^,\s]+))/gi;
+  const regEx = /((updates?|resolves?|closes?):? \"?([A-Z][A-Z0-9_]+\-[0-9]+)\"?)/gi;
```
Comment (juliangieseke) [inline src/functions/parseCommitBody.js:12]: Changed regex to follow this site: https://confluence.atlassian.com/adminjiraserver072/changing-the-project-key-format-828787722.html
